DROP TABLE IF EXISTS hot_history;
DROP TABLE IF EXISTS hot_item;
DROP TABLE IF EXISTS source_platform;
DROP TABLE IF EXISTS hot_category;

CREATE TABLE source_platform (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(32) NOT NULL UNIQUE,
    logo VARCHAR(1024),
    status TINYINT NOT NULL DEFAULT 1,
    sort INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hot_category (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    code VARCHAR(32) NOT NULL UNIQUE,
    status TINYINT NOT NULL DEFAULT 1,
    sort INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hot_item (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    source VARCHAR(32) NOT NULL,
    source_item_key VARCHAR(128) NOT NULL,
    source_url VARCHAR(1024),
    category VARCHAR(32) NOT NULL DEFAULT 'GENERAL',
    hot_value BIGINT NOT NULL DEFAULT 0,
    hot_value_text VARCHAR(32) NOT NULL DEFAULT '0',
    `rank` INT NOT NULL DEFAULT 0,
    previous_rank INT,
    rank_change INT NOT NULL DEFAULT 0,
    trend VARCHAR(16) NOT NULL DEFAULT 'STABLE',
    cover VARCHAR(1024),
    published_at TIMESTAMP,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE (source, source_item_key)
);

CREATE TABLE hot_history (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    hot_id BIGINT NOT NULL,
    hot_value BIGINT NOT NULL,
    `rank` INT NOT NULL DEFAULT 0,
    recorded_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_test_history_item FOREIGN KEY (hot_id) REFERENCES hot_item (id)
);
